authapp/urls.py
from django.urls import path

from . import views


app_name = 'authapp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

employee_management/urls.py
from django.contrib import admin
from django.urls import path, include
from employee.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('auth/', include('authapp.urls')),
    path('employee/', include('employee.urls'))
]

templates/includes/form.html
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="text-capitalize">{{ form.name.label }}</label>
        {{ form.name }}
        {% for error in form.name.errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}
    </div>
    <div class="form-group">
        <label for="email" class="text-capitalize">{{ form.email.label }}</label>
        {{ form.email }}
        {% for error in form.email.errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}
    </div>
    <div class="form-group">
        <label for="phone" class="text-capitalize">{{ form.phone.label }}</label>
        {{ form.phone }}
        {% for error in form.phone.errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}
    </div>
    <div class="form-group">
        <label for="department" class="text-capitalize">{{ form.department.label }}</label>
        {{ form.department }}
        {% for error in form.department.errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}
    </div>
    <div class="form-group">
        <label for="role" class="text-capitalize">{{ form.role.label }}</label>
        {{ form.role }}
        {% for error in form.role.errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}
    </div>
    <div class="form-group">
        <label for="joined_date" class="text-capitalize">{{ form.joined_date.label }}</label>
        {{ form.joined_date }}
        {% for error in form.joined_date.errors %}<small class="text-danger">{{ error|escape }}</small>{% endfor %}
    </div>
    <div class="d-grid gap-2 mt-4">
        {% if request.resolver_match.url_name == 'update' %}
            <button type="submit" class="btn btn-dark">Update Employee</button>
        {% elif request.resolver_match.url_name == 'add' %}
            <button type="submit" class="btn btn-dark">Add Employee</button>
        {% endif %}
    </div>
</form>

templates/includes/messages.html
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show"
         role="alert">
        {{ message }}
        <button type="button"
                class="btn-close"
                data-bs-dismiss="alert"
                aria-label="Close"></button>
    </div>
{% endfor %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">iEmployee</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <p class="mt-2">
                            Welcome <strong>{{ request.user.username }}</strong>
                        </p>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>