authapp/urls.py
from django.urls import path

from . import views


app_name = 'authapp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

employee/urls.py
from django.urls import path

from . import views

app_name = 'employee'

urlpatterns = [
    path("", views.view_all, name='view_all'),
    path('<int:id>/', views.view_single_employee, name='view_single_employee'),
    path('add/', views.add, name='add'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

employee_management/urls.py
from django.contrib import admin
from django.urls import path, include
from employee.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('auth/', include('authapp.urls')),
    path('employee/', include('employee.urls'))
]

employee/models.py
from django.db import models


class Department(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Role(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=12)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    joined_date = models.DateTimeField()

    def __str__(self):
        return self.name

employee/forms.py
from django import forms

from .models import Employee


class AddEmployeeForm(forms.ModelForm):
    phone = forms.CharField(max_length=12, widget=forms.NumberInput())
    joined_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    class Meta:
        model = Employee
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AddEmployeeForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Enter Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email'
        self.fields['phone'].widget.attrs['placeholder'] = 'Phone Number'

        # Set custom text for the first option of department field
        self.fields['department'].empty_label = 'Select Department'
        # Set custom text for the first option of role field
        self.fields['role'].empty_label = 'Select Role'

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].widget.attrs['required'] = True

employee/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q

from .models import Employee
from .forms import AddEmployeeForm


@login_required(login_url='authapp:login')
def index(request):
    context = dict()
    context['employees'] = Employee.objects.all().order_by('-joined_date')[:5]
    return render(request, 'employee/index.html', context)


@login_required(login_url='authapp:login')
def view_all(request):
    context = dict()
    search = ''
    try:
        search = request.GET['search']
    except:
        pass
    context['employees'] = Employee.objects.all().order_by('-joined_date')
    if search is not None:
        print(search)
        context['employees'] = Employee.objects.filter(
            Q(name__icontains=search) |
            Q(email__icontains=search) |
            Q(phone__icontains=search) |
            Q(department__name__icontains=search) |
            Q(role__name__icontains=search)
        ).order_by('-joined_date')
    return render(request, 'employee/view_all.html', context)


@login_required(login_url='authapp:login')
def view_single_employee(request, id):
    context = dict()
    try:
        employee = Employee.objects.get(pk=id)
    except:
        pass

    context['employee'] = employee

    return render(request, 'employee/employee.html', context)


@login_required(login_url='authapp:login')
def add(request):
    context = dict()
    context['form'] = AddEmployeeForm()
    if request.method == 'POST':
        form = AddEmployeeForm(request.POST)
        context['form'] = form
        if form.is_valid():
            form.save()
            messages.info(request, 'Employee added successfully.')
            return redirect('index')
        else:
            return render(request, 'employee/add.html', context)
    else:
        context['form'] = AddEmployeeForm()
    return render(request, 'employee/add.html', context)


@login_required(login_url='authapp:login')
def update(request, id):
    context = dict()
    try:
        employee = Employee.objects.get(pk=id)
    except Employee.DoesNotExist:
        messages.error(request, f'Empoyee does not exist with id {id}')
        return render(request, 'employee/update.html', context)

    form = AddEmployeeForm(instance=employee)
    context['form'] = form

    if request.method == 'POST':
        form = AddEmployeeForm(request.POST, instance=employee)
        context['form'] = form
        if form.is_valid():
            form.save()
            messages.info(request, 'Employee updated successfully.')
            return redirect('employee:view_single_employee', employee.id)
    print(request.resolver_match.url_name)
    return render(request, 'employee/update.html', context)


@login_required(login_url='authapp:login')
def delete(request, id):
    try:
        employee = Employee.objects.get(pk=id)
    except Employee.DoesNotExist:
        messages.error(request, 'Employee does not exist.')
        return redirect('employee:view_all')

    employee.delete()

    messages.info(request, 'Employee deleted successfully.')
    return redirect('employee:view_all')

templates/employee/add.html
{% extends "../base.html" %}
{% block title %}
    Add
{% endblock title %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                {% include "../includes/form.html" %}
                <div class="d-grid gap-2 mt-4">
                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-dark">Go Back</a>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
{% endblock main %}

templates/employee/employee.html
{% extends "../base.html" %}
{% block title %}
    Details
{% endblock title %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 text-center">
                <h1>
                    <strong>Name</strong> : {{ employee.name }}
                </h1>
                <p>
                    <strong>Email</strong> : {{ employee.email }}
                </p>
                <p>
                    <strong>Phone Number</strong> : {{ employee.phone }}
                </p>
                <p>
                    <strong>Department</strong> : {{ employee.department.name }}
                </p>
                <p>
                    <strong>Role</strong> : {{ employee.role.name }}
                </p>
                <p>
                    <strong>Joined Date</strong> : {{ employee.joined_date }}
                </p>
                <a href="{{ request.META.HTTP_REFERER }}"
                   class="text-decoration-none d-block mt-4 btn btn-dark">Go Back</a>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock main %}

templates/employee/index.html
{% extends "../base.html" %}
{% block title %}
    Home
{% endblock title %}
{% block main %}
    <div class="container">
        <h1 class="text-center">Welcome to Employee Management Application</h1>
        <hr>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 mb-2">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a class="btn btn-primary"
                       href="{% url 'employee:view_all' %}"
                       role="button">View All Employees</a>
                    <a class="btn btn-primary" href="{% url 'employee:add' %}" role="button">Add an Employee</a>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                {% for employee in employees %}
                    <h2>
                        <strong>{{ forloop.counter }}.</strong><a href="{% url 'employee:view_single_employee' employee.id %}"
   class="text-decoration-none">&#160;{{ employee.name }}</a>
                    </h2>
                {% endfor %}
                <a href="{% url 'employee:view_all' %}"
                   class="d-block mt-4 text-decoration-none">Click Here to See All</a>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock main %}

templates/employee/update.html
{% extends "../base.html" %}
{% block title %}
    Add
{% endblock title %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                {% include "../includes/form.html" %}
                <div class="d-grid gap-2 mt-4">
                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-dark">Go Back</a>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
{% endblock main %}

templates/employee/view_all.html
{% extends "../base.html" %}
{% block title %}
    All
{% endblock title %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <form class="d-flex mb-4" role="search">
                            <input class="form-control me-2"
                                   name="search"
                                   type="search"
                                   placeholder="Search Here..."
                                   required
                                   aria-label="Search">
                            <button class="btn btn-success" type="submit">Search</button>
                        </form>
                    </div>
                    <div class="col-md-2">
                        <a href="{% url 'employee:view_all' %}" class="btn btn-dark">View All</a>
                    </div>
                </div>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Phone</th>
                            <th scope="col">Department</th>
                            <th scope="col">Role</th>
                            <th scope="col">Joined Date</th>
                            <th scope="col">Operation</th>
                        </tr>
                    </thead>
                    {% for employee in employees %}
                        <tbody>
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ employee.name }}</td>
                                <td>{{ employee.email }}</td>
                                <td>{{ employee.phone }}</td>
                                <td>{{ employee.department.name }}</td>
                                <td>{{ employee.role.name }}</td>
                                <td>{{ employee.joined_date }}</td>
                                <td>
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{% url 'employee:view_single_employee' employee.id %}"
                                           class="btn btn-primary">Go</a>
                                        <a href="{% url 'employee:update' employee.id %}" class="btn btn-info">
                                            <i class="bi bi-pencil-fill"></i>
                                        </a>
                                        <a href="{% url 'employee:delete' employee.id %}" class="btn btn-danger">
                                            <i class="bi bi-x-lg"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{{ request.META.HTTP_REFERER }}"
                   class="text-decoration-none d-block mt-4 mb-4 btn btn-dark">Go Back</a>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock main %}